version: '3.7'

services:
  frontend:
    build:
      context: Frontend
      dockerfile: dev.dockerfile
    working_dir: /usr/src/frontend
    volumes:
      - ./Frontend/:/usr/src/frontend
      - /usr/src/frontend/node_modules
    ports:
     - '4200:4200'
     - '49153:49153'
     - '9876:9876'
     - '49152:49152'
    expose:
     - '4200'
     - '49153'
     - '9876'
     - '49152'
    command: /bin/sh start.sh

  backend:
    build:
      context: Backend
      dockerfile: dev.dockerfile
    working_dir: /usr/src/backend
    volumes:
      - ./Backend/:/usr/src/backend
    ports:
      - '8000:8000'
    expose:
      - '8000'
    command: python3 app.py